---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyperfine
description: My slightly simplified version of bluefin.

base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: latest

modules:
  - type: script
    scripts:
      - disable-extensions.sh
      - remove-starship.sh

  - type: dnf
    remove:
      packages:
        - tailscale
        - fish
        - tmux
        - zsh
        - glow
