---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyperfine
description: My slightly simplified version of bluefin.

base-image: ghcr.io/ublue-os/bluefin-nvidia-open
image-version: latest

modules:
  - type: script
    snippets:
      - "rm -f /etc/profile.d/90-bluefin-starship.sh"
      - "rm -f /usr/bin/starship"

  - type: dnf
    remove:
      packages:
        - tailscale
        - fish
        - tmux
        - zsh
  - type: systemd
    system:
      disabled:
        - tailscaled.service
